string object
uint8 prefered_hand_to_handover
---
# No result
---
int8 state

int8 STATE_COMPUTING_REBA=1
int8 STATE_COMPUTING_TRAJECTORIES=2
int8 STATE_RUNNING_TRAJECTORY_TO_OBJECT=3
int8 STATE_GRASPING_OBJECT=4
int8 STATE_RUNNING_TRAJECTORY_TO_HANDOVER=5
int8 STATE_WAITING_HUMAN_GRASP=6

