#!/usr/bin/env python
import rospy
import yaml
import sys
import tf
import roslib.packages


def main():
    obj = sys.argv[1]
    base = sys.argv[2]
    filename = sys.argv[3]

    tfl = tf.TransformListener()
    rospy.sleep(1)
    # get the transformation
    try:
        transform = tfl.lookupTransform(base, obj, rospy.Time(0))
    except Exception, e:
        raise

    pkg_dir = roslib.packages.get_pkg_dir("reba_optim")

    with open(pkg_dir+'/config/'+filename+'.yaml', 'w') as outfile:
        yaml.dump(transform, outfile, default_flow_style=True)
    return 0

if __name__ == '__main__':
    rospy.init_node('record_pose')
    main()
